### PR TITLE
Fix #59: Reduce content model of command

### LINKED ISSUE #59: Reduce content model of command
## Problem Description

In version 1.0.2.1 of GeekoDoc, `command` allows the following child elements:

```
alt, annotation, date, emphasis, firstterm, footnote, foreignphrase,
glossterm, indexterm, inlinemediaobject, link, phrase, quote, remark,
replaceable, subscript, superscript, trademark, xref.
```

This is too broad, we need a reduced content model.

## Expected Behaviour

Reduce it to `emphasis`(?), `phrase`, `replaceable`

### PR DESCRIPTION
**Pull request by tomschr**
This PR contains the following changes:

* Allow only text, emphasis, phrase, and replaceable
* Add testcase

### CODE REVIEW

**Comment by sknorr** [comment]
The basic changes here look good, so r+ (but haven't tried it). However, what I am wondering about is -- phrase and emphasis and perhaps even replaceable probably have a very lenient content model. That would probably allow circumventing all content restrictions for command, no? And there's no hope for fixing that, I guess.

However, in addition could you check the content model of replaceable as well please? At least this one should not become the element that allows all the command-foreign stuff to creep in.

**Comment by tomschr** [comment]
> However, what I am wondering about is -- `phrase` and `emphasis` and perhaps even `replaceable` probably have a very lenient content model.

That's true, the content model is broader than `command` itself.

For example, `phrase` is originally defined as:

```
db.phrase =
    ## A span of text
    element phrase { db.phrase.attlist, db.all.inlines* }
```

Depending on what inlines we've enabled, it contains more or less a bunch of other inlines that may or may not be useful (see below).

> That would probably allow circumventing all content restrictions for command, no? And there's no hope for fixing that, I guess.

Yes, it can be (ab)used as such, unfortunately.


> However, in addition could you check the content model of `replaceable` as well please? At least this one should not become the element that allows all the command-foreign stuff to creep in.

After all the changes, Geekdoc allows the following elements inside `replaceable` (and `phrase` and `emphasis`):

```
alt, annotation, co, date, emphasis, firstterm, footnote, foreignphrase, glossterm,
indexterm, inlinemediaobject, link, phrase, quote, remark, subscript, superscript,
trademark, xref,
text
```

Well, it looks indeed a bit broad and it *could* be reduced. I'm not against that. However, I would suggest to open a separate issue to separate it from this bug.

**Comment by taroth21** [comment]
> After all the changes, Geekdoc allows the following elements inside `replaceable` (and `phrase` and `emphasis`):
> 
> ```
> alt, annotation, co, date, emphasis, firstterm, footnote, foreignphrase, glossterm,
> indexterm, inlinemediaobject, link, phrase, quote, remark, subscript, superscript,
> trademark, xref,
> text
> ```
> 
> Well, it looks indeed a bit broad and it _could_ be reduced. I'm not against that. However, I would suggest to open a separate issue to separate it from this bug. 

+1, the content model for replaceable should definitely be reduced.

**Comment by sknorr** [comment]
Issue opened -- https://github.com/openSUSE/geekodoc/issues/69

**Pull request merged**
